-- Generated by SQL Maestro for MySQL. Release date 14/05/2008
-- 19/03/2009 01:56:28 p.m.
-- ----------------------------------
-- Alias: help at localhost
-- Database name: help
-- Host: localhost
-- Port number: 3306
-- User name: root
-- Server: 5.0.45-community-nt-log
-- Session ID: 59
-- Character set: ascii
-- Collation: ascii_general_ci


SET FOREIGN_KEY_CHECKS=0;

DROP DATABASE IF EXISTS `help`;

CREATE DATABASE `help`
  CHARACTER SET `ascii`
  COLLATE `ascii_general_ci`;

USE `help`;

/* Tables */
DROP TABLE IF EXISTS `area`;

CREATE TABLE `area` (
  `idarea`   int NOT NULL,
  `nombre`   varchar(20) NOT NULL,
  `fkemple`  int,
  PRIMARY KEY (`idarea`)
) ENGINE = InnoDB;

/* Data for table "area" */
INSERT INTO `area` (`idarea`, `nombre`, `fkemple`) VALUES (1, 'Sistemas', 1);
INSERT INTO `area` (`idarea`, `nombre`, `fkemple`) VALUES (123, 'INFORMATICA', 1);
INSERT INTO `area` (`idarea`, `nombre`, `fkemple`) VALUES (7777, '7777', 7777);
COMMIT;


/* Procedures */
DROP PROCEDURE IF EXISTS `pa_insertararea`;

DELIMITER |

CREATE PROCEDURE `pa_insertararea` 
(
  IN  `idarea`   int,
  IN  `nombre`   varchar(20),
  IN  `fkemple`  int
)
BEGIN
  /* Procedure text */
  insert into area values (idarea,nombre,fkemple);
END|

DELIMITER ;